// Code generated by go generate; DO NOT EDIT.

package uint256

import (
	"math/big"
	"testing"
)

func TestNew192(t *testing.T) {
	u := New192(42)
	if u.String() != "42" {
		t.Fatalf("got %s, want 42", u.String())
	}
}

func TestNew192FromString(t *testing.T) {
	u, err := New192FromString(maxBigInt192.String())
	if err != nil {
		t.Fatal(err)
	}
	if !u.Equal(Max192()) {
		t.Fatal("expected max value")
	}

	if _, err := New192FromString("-1"); err == nil {
		t.Fatal("expected error for negative")
	}

	overflow := new(big.Int).Add(maxBigInt192, big.NewInt(1)).String()
	if _, err := New192FromString(overflow); err == nil {
		t.Fatal("expected error for overflow")
	}
	if _, err := New192FromString("1.5"); err == nil {
		t.Fatal("expected error for fractional")
	}
}

func TestNew192FromBigInt(t *testing.T) {
	b := new(big.Int).SetUint64(1000)
	u, err := New192FromBigInt(b)
	if err != nil {
		t.Fatal(err)
	}
	if u.String() != "1000" {
		t.Fatalf("got %s", u.String())
	}
}

func TestNew192FromWords(t *testing.T) {
	words := [3]uint64{}
	words[2] = 1
	u := New192FromWords(words[0], words[1], words[2])
	if u.String() != "1" {
		t.Fatalf("want 1, got %s", u.String())
	}

	u1 := New192FromWords(0x1, 0x2, 0x3)
	u2, _ := New192FromBigInt(u1.BigInt())
	if u1 != u2 {
		t.Fatal("round-trip BigInt mismatch")
	}
}

func TestUint192Arithmetic(t *testing.T) {
	a := New192(100)
	b := New192(42)

	sum, err := a.Add(b)
	if err != nil || sum.String() != "142" {
		t.Fatalf("Add: got %v %v", sum, err)
	}

	diff, err := a.Sub(b)
	if err != nil || diff.String() != "58" {
		t.Fatalf("Sub: got %v %v", diff, err)
	}

	if _, err := b.Sub(a); err == nil {
		t.Fatal("Sub underflow: expected error")
	}

	prod, err := a.Mul(b)
	if err != nil || prod.String() != "4200" {
		t.Fatalf("Mul: got %v %v", prod, err)
	}

	quot, err := a.Div(b)
	if err != nil || quot.String() != "2" {
		t.Fatalf("Div: got %v %v", quot, err)
	}

	rem, err := a.Mod(b)
	if err != nil || rem.String() != "16" {
		t.Fatalf("Mod: got %v %v", rem, err)
	}

	if _, err := a.Div(Zero192()); err == nil {
		t.Fatal("Div by zero: expected error")
	}
}

func TestUint192Overflow(t *testing.T) {
	m := Max192()
	if _, err := m.Add(New192(1)); err == nil {
		t.Fatal("expected overflow error")
	}
	if _, err := m.Mul(New192(2)); err == nil {
		t.Fatal("expected overflow error")
	}
}

func TestBytes24(t *testing.T) {
	u := New192(256)
	b := u.Bytes24()
	if b[22] != 1 || b[23] != 0 {
		t.Fatalf("unexpected bytes: %v", b)
	}
}

func TestUint192MapKey(t *testing.T) {
	m := map[Uint192]string{}
	a, b := New192(1), New192(2)
	m[a] = "one"
	m[b] = "two"
	if m[a] != "one" || m[b] != "two" {
		t.Fatal("map key lookup failed")
	}
	a2 := New192(1)
	if a != a2 {
		t.Fatal("struct equality failed")
	}
}

func TestUint192Cmp(t *testing.T) {
	a, b := New192(10), New192(20)
	if a.Cmp(b) != -1 || b.Cmp(a) != 1 || a.Cmp(a) != 0 {
		t.Fatal("Cmp wrong")
	}
	if !a.Lt(b) || !b.Gt(a) || !a.Lte(a) || !a.Gte(a) {
		t.Fatal("comparison methods wrong")
	}
}

func TestUint192Bitwise(t *testing.T) {
	a := New192FromWords(0, 0, 0b1010)
	b := New192FromWords(0, 0, 0b1100)

	if got := a.And(b); got.String() != "8" {
		t.Fatalf("And: got %s, want 8", got)
	}
	if got := a.Or(b); got.String() != "14" {
		t.Fatalf("Or: got %s, want 14", got)
	}
	if got := a.Xor(b); got.String() != "6" {
		t.Fatalf("Xor: got %s, want 6", got)
	}
	if got := a.AndNot(b); got.String() != "2" {
		t.Fatalf("AndNot: got %s, want 2", got)
	}

	if got := a.Not().And(New192(0xF)); got.String() != "5" {
		t.Fatalf("Not masked low nibble: got %s, want 5", got)
	}

	if got := New192(1).Lsh(1); got.String() != "2" {
		t.Fatalf("Lsh 1: got %s, want 2", got)
	}
	if got := New192(8).Rsh(1); got.String() != "4" {
		t.Fatalf("Rsh 1: got %s, want 4", got)
	}

	if got := New192(1).Lsh(64); got.Cmp(New192FromWords(0, 1, 0)) != 0 {
		t.Fatalf("Lsh 64: got %v", got)
	}
	if got := New192FromWords(0, 1, 0).Rsh(64); got.String() != "1" {
		t.Fatalf("Rsh 64: got %s, want 1", got)
	}

	if !New192(1).Lsh(192).IsZero() {
		t.Fatal("Lsh >= bit width should be zero")
	}
	if !New192(1).Rsh(192).IsZero() {
		t.Fatal("Rsh >= bit width should be zero")
	}
}
