// Code generated by go generate; DO NOT EDIT.

package uint256

import (
	"encoding/binary"
	"fmt"
	"math/big"

	"github.com/shopspring/decimal"
)

var (
	maxBigInt192 = new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), 192), big.NewInt(1))
	decMax192    = decimal.NewFromBigInt(maxBigInt192, 0)
)

// Uint192 is an unsigned 192-bit integer stored as 3 big-endian uint64 words.
// v[0] holds the most significant word; v[2] holds the least significant word.
// The struct is comparable and can be used as a map key.
type Uint192 struct {
	v [3]uint64
}

// --- internal helpers ---

func arr192ToBigInt(v [3]uint64) *big.Int {
	var buf [24]byte
	for i := 0; i < 3; i++ {
		binary.BigEndian.PutUint64(buf[i*8:(i+1)*8], v[i])
	}
	return new(big.Int).SetBytes(buf[:])
}

func bigIntToArr192(b *big.Int) [3]uint64 {
	raw := b.Bytes()
	var buf [24]byte
	copy(buf[24-len(raw):], raw)

	var v [3]uint64
	for i := 0; i < 3; i++ {
		v[i] = binary.BigEndian.Uint64(buf[i*8 : (i+1)*8])
	}
	return v
}

func (u Uint192) toDecimal() decimal.Decimal {
	return decimal.NewFromBigInt(arr192ToBigInt(u.v), 0)
}

func validate192(d decimal.Decimal) error {
	if d.Sign() < 0 {
		return fmt.Errorf("uint192: negative value %s", d)
	}
	if d.GreaterThan(decMax192) {
		return fmt.Errorf("uint192: overflow %s", d)
	}
	if !d.Equal(d.Floor()) {
		return fmt.Errorf("uint192: fractional value %s", d)
	}
	return nil
}

func fromDecimal192(d decimal.Decimal) (Uint192, error) {
	if err := validate192(d); err != nil {
		return Uint192{}, err
	}
	b, _ := new(big.Int).SetString(d.String(), 10)
	return Uint192{v: bigIntToArr192(b)}, nil
}

// --- constructors ---

// New192 creates a Uint192 from a uint64.
func New192(val uint64) Uint192 {
	return Uint192{v: [3]uint64{0, 0, val}}
}

// New192FromString parses a decimal integer string.
func New192FromString(s string) (Uint192, error) {
	d, err := decimal.NewFromString(s)
	if err != nil {
		return Uint192{}, err
	}
	return fromDecimal192(d)
}

// New192FromBigInt creates a Uint192 from a *big.Int.
func New192FromBigInt(b *big.Int) (Uint192, error) {
	if b.Sign() < 0 {
		return Uint192{}, fmt.Errorf("uint192: negative value")
	}
	if b.Cmp(maxBigInt192) > 0 {
		return Uint192{}, fmt.Errorf("uint192: overflow")
	}
	return Uint192{v: bigIntToArr192(b)}, nil
}

// New192FromWords creates a Uint192 from 3 64-bit words in big-endian order.
func New192FromWords(w0 uint64, w1 uint64, w2 uint64) Uint192 {
	return Uint192{v: [3]uint64{w0, w1, w2}}
}

// Zero192 returns the zero value.
func Zero192() Uint192 { return Uint192{} }

// Max192 returns the maximum uint192 value (2^192 - 1).
func Max192() Uint192 {
	return Uint192{v: [3]uint64{^uint64(0), ^uint64(0), ^uint64(0)}}
}

// --- arithmetic (via shopspring/decimal) ---

// Add returns u + v, or an error on overflow.
func (u Uint192) Add(v Uint192) (Uint192, error) {
	return fromDecimal192(u.toDecimal().Add(v.toDecimal()))
}

// Sub returns u - v, or an error on underflow.
func (u Uint192) Sub(v Uint192) (Uint192, error) {
	if u.Cmp(v) < 0 {
		return Uint192{}, fmt.Errorf("uint192: underflow")
	}
	b, _ := new(big.Int).SetString(u.toDecimal().Sub(v.toDecimal()).String(), 10)
	return Uint192{v: bigIntToArr192(b)}, nil
}

// Mul returns u * v, or an error on overflow.
func (u Uint192) Mul(v Uint192) (Uint192, error) {
	return fromDecimal192(u.toDecimal().Mul(v.toDecimal()))
}

// Div returns floor(u / v), or an error on division by zero.
func (u Uint192) Div(v Uint192) (Uint192, error) {
	if v.IsZero() {
		return Uint192{}, fmt.Errorf("uint192: division by zero")
	}
	return fromDecimal192(u.toDecimal().Div(v.toDecimal()).Floor())
}

// Mod returns u mod v, or an error on division by zero.
func (u Uint192) Mod(v Uint192) (Uint192, error) {
	if v.IsZero() {
		return Uint192{}, fmt.Errorf("uint192: division by zero")
	}
	return fromDecimal192(u.toDecimal().Mod(v.toDecimal()))
}

// --- bitwise operations ---

// Not returns bitwise complement of u.
func (u Uint192) Not() Uint192 {
	var out Uint192
	for i := 0; i < 3; i++ {
		out.v[i] = ^u.v[i]
	}
	return out
}

// And returns u & w.
func (u Uint192) And(w Uint192) Uint192 {
	var out Uint192
	for i := 0; i < 3; i++ {
		out.v[i] = u.v[i] & w.v[i]
	}
	return out
}

// Or returns u | w.
func (u Uint192) Or(w Uint192) Uint192 {
	var out Uint192
	for i := 0; i < 3; i++ {
		out.v[i] = u.v[i] | w.v[i]
	}
	return out
}

// Xor returns u ^ w.
func (u Uint192) Xor(w Uint192) Uint192 {
	var out Uint192
	for i := 0; i < 3; i++ {
		out.v[i] = u.v[i] ^ w.v[i]
	}
	return out
}

// AndNot returns u &^ w (bit clear).
func (u Uint192) AndNot(w Uint192) Uint192 {
	var out Uint192
	for i := 0; i < 3; i++ {
		out.v[i] = u.v[i] &^ w.v[i]
	}
	return out
}

// Lsh returns u << n. Bits shifted out are discarded.
func (u Uint192) Lsh(n uint) Uint192 {
	if n == 0 {
		return u
	}
	if n >= 192 {
		return Uint192{}
	}

	wordShift := int(n / 64)
	bitShift := n % 64

	var out Uint192
	for i := 0; i < 3; i++ {
		src := i + wordShift
		if src >= 3 {
			continue
		}

		out.v[i] = u.v[src] << bitShift
		if bitShift != 0 && src+1 < 3 {
			out.v[i] |= u.v[src+1] >> (64 - bitShift)
		}
	}
	return out
}

// Rsh returns u >> n. Bits shifted out are discarded.
func (u Uint192) Rsh(n uint) Uint192 {
	if n == 0 {
		return u
	}
	if n >= 192 {
		return Uint192{}
	}

	wordShift := int(n / 64)
	bitShift := n % 64

	var out Uint192
	for i := 2; i >= 0; i-- {
		src := i - wordShift
		if src < 0 {
			continue
		}

		out.v[i] = u.v[src] >> bitShift
		if bitShift != 0 && src-1 >= 0 {
			out.v[i] |= u.v[src-1] << (64 - bitShift)
		}
	}
	return out
}

// --- comparisons (direct on words, no decimal allocation) ---

// Cmp returns -1, 0, or 1 if u < v, u == v, or u > v.
func (u Uint192) Cmp(w Uint192) int {
	for i := 0; i < 3; i++ {
		if u.v[i] < w.v[i] {
			return -1
		}
		if u.v[i] > w.v[i] {
			return 1
		}
	}
	return 0
}

func (u Uint192) Equal(w Uint192) bool { return u == w }
func (u Uint192) Lt(w Uint192) bool    { return u.Cmp(w) < 0 }
func (u Uint192) Gt(w Uint192) bool    { return u.Cmp(w) > 0 }
func (u Uint192) Lte(w Uint192) bool   { return u.Cmp(w) <= 0 }
func (u Uint192) Gte(w Uint192) bool   { return u.Cmp(w) >= 0 }
func (u Uint192) IsZero() bool         { return u.v == [3]uint64{} }

// --- conversions ---

// String returns the decimal string representation.
func (u Uint192) String() string { return arr192ToBigInt(u.v).String() }

// BigInt returns the value as a *big.Int.
func (u Uint192) BigInt() *big.Int { return arr192ToBigInt(u.v) }

// Bytes24 returns the 192-bit big-endian byte representation.
func (u Uint192) Bytes24() [24]byte {
	var buf [24]byte
	for i := 0; i < 3; i++ {
		binary.BigEndian.PutUint64(buf[i*8:(i+1)*8], u.v[i])
	}
	return buf
}
