// Code generated by go generate; DO NOT EDIT.

package uint256

import (
	"math/big"
	"testing"
)

func TestNew320(t *testing.T) {
	u := New320(42)
	if u.String() != "42" {
		t.Fatalf("got %s, want 42", u.String())
	}
}

func TestNew320FromString(t *testing.T) {
	u, err := New320FromString(maxBigInt320.String())
	if err != nil {
		t.Fatal(err)
	}
	if !u.Equal(Max320()) {
		t.Fatal("expected max value")
	}

	if _, err := New320FromString("-1"); err == nil {
		t.Fatal("expected error for negative")
	}

	overflow := new(big.Int).Add(maxBigInt320, big.NewInt(1)).String()
	if _, err := New320FromString(overflow); err == nil {
		t.Fatal("expected error for overflow")
	}
	if _, err := New320FromString("1.5"); err == nil {
		t.Fatal("expected error for fractional")
	}
}

func TestNew320FromBigInt(t *testing.T) {
	b := new(big.Int).SetUint64(1000)
	u, err := New320FromBigInt(b)
	if err != nil {
		t.Fatal(err)
	}
	if u.String() != "1000" {
		t.Fatalf("got %s", u.String())
	}
}

func TestNew320FromWords(t *testing.T) {
	words := [5]uint64{}
	words[4] = 1
	u := New320FromWords(words[0], words[1], words[2], words[3], words[4])
	if u.String() != "1" {
		t.Fatalf("want 1, got %s", u.String())
	}

	u1 := New320FromWords(0x1, 0x2, 0x3, 0x4, 0x5)
	u2, _ := New320FromBigInt(u1.BigInt())
	if u1 != u2 {
		t.Fatal("round-trip BigInt mismatch")
	}
}

func TestUint320Arithmetic(t *testing.T) {
	a := New320(100)
	b := New320(42)

	sum, err := a.Add(b)
	if err != nil || sum.String() != "142" {
		t.Fatalf("Add: got %v %v", sum, err)
	}

	diff, err := a.Sub(b)
	if err != nil || diff.String() != "58" {
		t.Fatalf("Sub: got %v %v", diff, err)
	}

	if _, err := b.Sub(a); err == nil {
		t.Fatal("Sub underflow: expected error")
	}

	prod, err := a.Mul(b)
	if err != nil || prod.String() != "4200" {
		t.Fatalf("Mul: got %v %v", prod, err)
	}

	quot, err := a.Div(b)
	if err != nil || quot.String() != "2" {
		t.Fatalf("Div: got %v %v", quot, err)
	}

	rem, err := a.Mod(b)
	if err != nil || rem.String() != "16" {
		t.Fatalf("Mod: got %v %v", rem, err)
	}

	if _, err := a.Div(Zero320()); err == nil {
		t.Fatal("Div by zero: expected error")
	}
}

func TestUint320Overflow(t *testing.T) {
	m := Max320()
	if _, err := m.Add(New320(1)); err == nil {
		t.Fatal("expected overflow error")
	}
	if _, err := m.Mul(New320(2)); err == nil {
		t.Fatal("expected overflow error")
	}
}

func TestBytes40(t *testing.T) {
	u := New320(256)
	b := u.Bytes40()
	if b[38] != 1 || b[39] != 0 {
		t.Fatalf("unexpected bytes: %v", b)
	}
}

func TestUint320MapKey(t *testing.T) {
	m := map[Uint320]string{}
	a, b := New320(1), New320(2)
	m[a] = "one"
	m[b] = "two"
	if m[a] != "one" || m[b] != "two" {
		t.Fatal("map key lookup failed")
	}
	a2 := New320(1)
	if a != a2 {
		t.Fatal("struct equality failed")
	}
}

func TestUint320Cmp(t *testing.T) {
	a, b := New320(10), New320(20)
	if a.Cmp(b) != -1 || b.Cmp(a) != 1 || a.Cmp(a) != 0 {
		t.Fatal("Cmp wrong")
	}
	if !a.Lt(b) || !b.Gt(a) || !a.Lte(a) || !a.Gte(a) {
		t.Fatal("comparison methods wrong")
	}
}

func TestUint320Bitwise(t *testing.T) {
	a := New320FromWords(0, 0, 0, 0, 0b1010)
	b := New320FromWords(0, 0, 0, 0, 0b1100)

	if got := a.And(b); got.String() != "8" {
		t.Fatalf("And: got %s, want 8", got)
	}
	if got := a.Or(b); got.String() != "14" {
		t.Fatalf("Or: got %s, want 14", got)
	}
	if got := a.Xor(b); got.String() != "6" {
		t.Fatalf("Xor: got %s, want 6", got)
	}
	if got := a.AndNot(b); got.String() != "2" {
		t.Fatalf("AndNot: got %s, want 2", got)
	}

	if got := a.Not().And(New320(0xF)); got.String() != "5" {
		t.Fatalf("Not masked low nibble: got %s, want 5", got)
	}

	if got := New320(1).Lsh(1); got.String() != "2" {
		t.Fatalf("Lsh 1: got %s, want 2", got)
	}
	if got := New320(8).Rsh(1); got.String() != "4" {
		t.Fatalf("Rsh 1: got %s, want 4", got)
	}

	if got := New320(1).Lsh(64); got.Cmp(New320FromWords(0, 0, 0, 1, 0)) != 0 {
		t.Fatalf("Lsh 64: got %v", got)
	}
	if got := New320FromWords(0, 0, 0, 1, 0).Rsh(64); got.String() != "1" {
		t.Fatalf("Rsh 64: got %s, want 1", got)
	}

	if !New320(1).Lsh(320).IsZero() {
		t.Fatal("Lsh >= bit width should be zero")
	}
	if !New320(1).Rsh(320).IsZero() {
		t.Fatal("Rsh >= bit width should be zero")
	}
}
