package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
)

type templateData struct {
	Bits      int
	Words     int
	Bytes     int
	TypeName  string
	ArrType   string
	PreZeros  string
	WordsExpr string
}

const uintTemplate = `// Code generated by go generate; DO NOT EDIT.

package uint256

import (
	"encoding/binary"
	"fmt"
	"math/big"

	"github.com/shopspring/decimal"
)

var (
	maxBigInt{{.Bits}} = new(big.Int).Sub(new(big.Int).Lsh(big.NewInt(1), {{.Bits}}), big.NewInt(1))
	decMax{{.Bits}}    = decimal.NewFromBigInt(maxBigInt{{.Bits}}, 0)
)

// {{.TypeName}} is an unsigned {{.Bits}}-bit integer stored as {{.Words}} big-endian uint64 words.
// v[0] holds the most significant word; v[{{sub .Words 1}}] holds the least significant word.
// The struct is comparable and can be used as a map key.
type {{.TypeName}} struct {
	v {{.ArrType}}
}

// --- internal helpers ---

func arr{{.Bits}}ToBigInt(v {{.ArrType}}) *big.Int {
	var buf [{{.Bytes}}]byte
	for i := 0; i < {{.Words}}; i++ {
		binary.BigEndian.PutUint64(buf[i*8:(i+1)*8], v[i])
	}
	return new(big.Int).SetBytes(buf[:])
}

func bigIntToArr{{.Bits}}(b *big.Int) {{.ArrType}} {
	raw := b.Bytes()
	var buf [{{.Bytes}}]byte
	copy(buf[{{.Bytes}}-len(raw):], raw)

	var v {{.ArrType}}
	for i := 0; i < {{.Words}}; i++ {
		v[i] = binary.BigEndian.Uint64(buf[i*8 : (i+1)*8])
	}
	return v
}

func (u {{.TypeName}}) toDecimal() decimal.Decimal {
	return decimal.NewFromBigInt(arr{{.Bits}}ToBigInt(u.v), 0)
}

func validate{{.Bits}}(d decimal.Decimal) error {
	if d.Sign() < 0 {
		return fmt.Errorf("uint{{.Bits}}: negative value %s", d)
	}
	if d.GreaterThan(decMax{{.Bits}}) {
		return fmt.Errorf("uint{{.Bits}}: overflow %s", d)
	}
	if !d.Equal(d.Floor()) {
		return fmt.Errorf("uint{{.Bits}}: fractional value %s", d)
	}
	return nil
}

func fromDecimal{{.Bits}}(d decimal.Decimal) ({{.TypeName}}, error) {
	if err := validate{{.Bits}}(d); err != nil {
		return {{.TypeName}}{}, err
	}
	b, _ := new(big.Int).SetString(d.String(), 10)
	return {{.TypeName}}{v: bigIntToArr{{.Bits}}(b)}, nil
}

// --- constructors ---

// New{{.Bits}} creates a {{.TypeName}} from a uint64.
func New{{.Bits}}(val uint64) {{.TypeName}} {
	return {{.TypeName}}{v: {{.ArrType}}{ {{.PreZeros}}{{if .PreZeros}}, {{end}}val }}
}

// New{{.Bits}}FromString parses a decimal integer string.
func New{{.Bits}}FromString(s string) ({{.TypeName}}, error) {
	d, err := decimal.NewFromString(s)
	if err != nil {
		return {{.TypeName}}{}, err
	}
	return fromDecimal{{.Bits}}(d)
}

// New{{.Bits}}FromBigInt creates a {{.TypeName}} from a *big.Int.
func New{{.Bits}}FromBigInt(b *big.Int) ({{.TypeName}}, error) {
	if b.Sign() < 0 {
		return {{.TypeName}}{}, fmt.Errorf("uint{{.Bits}}: negative value")
	}
	if b.Cmp(maxBigInt{{.Bits}}) > 0 {
		return {{.TypeName}}{}, fmt.Errorf("uint{{.Bits}}: overflow")
	}
	return {{.TypeName}}{v: bigIntToArr{{.Bits}}(b)}, nil
}

// New{{.Bits}}FromWords creates a {{.TypeName}} from {{.Words}} 64-bit words in big-endian order.
func New{{.Bits}}FromWords({{.WordsExpr}}) {{.TypeName}} {
	return {{.TypeName}}{v: {{.ArrType}}{ {{wordNames .Words}} }}
}

// Zero{{.Bits}} returns the zero value.
func Zero{{.Bits}}() {{.TypeName}} { return {{.TypeName}}{} }

// Max{{.Bits}} returns the maximum uint{{.Bits}} value (2^{{.Bits}} - 1).
func Max{{.Bits}}() {{.TypeName}} {
	return {{.TypeName}}{v: {{.ArrType}}{ {{repeatWord "^uint64(0)" .Words}} }}
}

// --- arithmetic (via shopspring/decimal) ---

// Add returns u + v, or an error on overflow.
func (u {{.TypeName}}) Add(v {{.TypeName}}) ({{.TypeName}}, error) {
	return fromDecimal{{.Bits}}(u.toDecimal().Add(v.toDecimal()))
}

// Sub returns u - v, or an error on underflow.
func (u {{.TypeName}}) Sub(v {{.TypeName}}) ({{.TypeName}}, error) {
	if u.Cmp(v) < 0 {
		return {{.TypeName}}{}, fmt.Errorf("uint{{.Bits}}: underflow")
	}
	b, _ := new(big.Int).SetString(u.toDecimal().Sub(v.toDecimal()).String(), 10)
	return {{.TypeName}}{v: bigIntToArr{{.Bits}}(b)}, nil
}

// Mul returns u * v, or an error on overflow.
func (u {{.TypeName}}) Mul(v {{.TypeName}}) ({{.TypeName}}, error) {
	return fromDecimal{{.Bits}}(u.toDecimal().Mul(v.toDecimal()))
}

// Div returns floor(u / v), or an error on division by zero.
func (u {{.TypeName}}) Div(v {{.TypeName}}) ({{.TypeName}}, error) {
	if v.IsZero() {
		return {{.TypeName}}{}, fmt.Errorf("uint{{.Bits}}: division by zero")
	}
	return fromDecimal{{.Bits}}(u.toDecimal().Div(v.toDecimal()).Floor())
}

// Mod returns u mod v, or an error on division by zero.
func (u {{.TypeName}}) Mod(v {{.TypeName}}) ({{.TypeName}}, error) {
	if v.IsZero() {
		return {{.TypeName}}{}, fmt.Errorf("uint{{.Bits}}: division by zero")
	}
	return fromDecimal{{.Bits}}(u.toDecimal().Mod(v.toDecimal()))
}

// --- bitwise operations ---

// Not returns bitwise complement of u.
func (u {{.TypeName}}) Not() {{.TypeName}} {
	var out {{.TypeName}}
	for i := 0; i < {{.Words}}; i++ {
		out.v[i] = ^u.v[i]
	}
	return out
}

// And returns u & w.
func (u {{.TypeName}}) And(w {{.TypeName}}) {{.TypeName}} {
	var out {{.TypeName}}
	for i := 0; i < {{.Words}}; i++ {
		out.v[i] = u.v[i] & w.v[i]
	}
	return out
}

// Or returns u | w.
func (u {{.TypeName}}) Or(w {{.TypeName}}) {{.TypeName}} {
	var out {{.TypeName}}
	for i := 0; i < {{.Words}}; i++ {
		out.v[i] = u.v[i] | w.v[i]
	}
	return out
}

// Xor returns u ^ w.
func (u {{.TypeName}}) Xor(w {{.TypeName}}) {{.TypeName}} {
	var out {{.TypeName}}
	for i := 0; i < {{.Words}}; i++ {
		out.v[i] = u.v[i] ^ w.v[i]
	}
	return out
}

// AndNot returns u &^ w (bit clear).
func (u {{.TypeName}}) AndNot(w {{.TypeName}}) {{.TypeName}} {
	var out {{.TypeName}}
	for i := 0; i < {{.Words}}; i++ {
		out.v[i] = u.v[i] &^ w.v[i]
	}
	return out
}

// Lsh returns u << n. Bits shifted out are discarded.
func (u {{.TypeName}}) Lsh(n uint) {{.TypeName}} {
	if n == 0 {
		return u
	}
	if n >= {{.Bits}} {
		return {{.TypeName}}{}
	}

	wordShift := int(n / 64)
	bitShift := n % 64

	var out {{.TypeName}}
	for i := 0; i < {{.Words}}; i++ {
		src := i + wordShift
		if src >= {{.Words}} {
			continue
		}

		out.v[i] = u.v[src] << bitShift
		if bitShift != 0 && src+1 < {{.Words}} {
			out.v[i] |= u.v[src+1] >> (64 - bitShift)
		}
	}
	return out
}

// Rsh returns u >> n. Bits shifted out are discarded.
func (u {{.TypeName}}) Rsh(n uint) {{.TypeName}} {
	if n == 0 {
		return u
	}
	if n >= {{.Bits}} {
		return {{.TypeName}}{}
	}

	wordShift := int(n / 64)
	bitShift := n % 64

	var out {{.TypeName}}
	for i := {{sub .Words 1}}; i >= 0; i-- {
		src := i - wordShift
		if src < 0 {
			continue
		}

		out.v[i] = u.v[src] >> bitShift
		if bitShift != 0 && src-1 >= 0 {
			out.v[i] |= u.v[src-1] << (64 - bitShift)
		}
	}
	return out
}

// --- comparisons (direct on words, no decimal allocation) ---

// Cmp returns -1, 0, or 1 if u < v, u == v, or u > v.
func (u {{.TypeName}}) Cmp(w {{.TypeName}}) int {
	for i := 0; i < {{.Words}}; i++ {
		if u.v[i] < w.v[i] {
			return -1
		}
		if u.v[i] > w.v[i] {
			return 1
		}
	}
	return 0
}

func (u {{.TypeName}}) Equal(w {{.TypeName}}) bool { return u == w }
func (u {{.TypeName}}) Lt(w {{.TypeName}}) bool    { return u.Cmp(w) < 0 }
func (u {{.TypeName}}) Gt(w {{.TypeName}}) bool    { return u.Cmp(w) > 0 }
func (u {{.TypeName}}) Lte(w {{.TypeName}}) bool   { return u.Cmp(w) <= 0 }
func (u {{.TypeName}}) Gte(w {{.TypeName}}) bool   { return u.Cmp(w) >= 0 }
func (u {{.TypeName}}) IsZero() bool               { return u.v == {{.ArrType}}{} }

// --- conversions ---

// String returns the decimal string representation.
func (u {{.TypeName}}) String() string { return arr{{.Bits}}ToBigInt(u.v).String() }

// BigInt returns the value as a *big.Int.
func (u {{.TypeName}}) BigInt() *big.Int { return arr{{.Bits}}ToBigInt(u.v) }

// Bytes{{.Bytes}} returns the {{.Bits}}-bit big-endian byte representation.
func (u {{.TypeName}}) Bytes{{.Bytes}}() [{{.Bytes}}]byte {
	var buf [{{.Bytes}}]byte
	for i := 0; i < {{.Words}}; i++ {
		binary.BigEndian.PutUint64(buf[i*8:(i+1)*8], u.v[i])
	}
	return buf
}
`

const testTemplate = `// Code generated by go generate; DO NOT EDIT.

package uint256

import (
	"math/big"
	"testing"
)

func TestNew{{.Bits}}(t *testing.T) {
	u := New{{.Bits}}(42)
	if u.String() != "42" {
		t.Fatalf("got %s, want 42", u.String())
	}
}

func TestNew{{.Bits}}FromString(t *testing.T) {
	u, err := New{{.Bits}}FromString(maxBigInt{{.Bits}}.String())
	if err != nil {
		t.Fatal(err)
	}
	if !u.Equal(Max{{.Bits}}()) {
		t.Fatal("expected max value")
	}

	if _, err := New{{.Bits}}FromString("-1"); err == nil {
		t.Fatal("expected error for negative")
	}

	overflow := new(big.Int).Add(maxBigInt{{.Bits}}, big.NewInt(1)).String()
	if _, err := New{{.Bits}}FromString(overflow); err == nil {
		t.Fatal("expected error for overflow")
	}
	if _, err := New{{.Bits}}FromString("1.5"); err == nil {
		t.Fatal("expected error for fractional")
	}
}

func TestNew{{.Bits}}FromBigInt(t *testing.T) {
	b := new(big.Int).SetUint64(1000)
	u, err := New{{.Bits}}FromBigInt(b)
	if err != nil {
		t.Fatal(err)
	}
	if u.String() != "1000" {
		t.Fatalf("got %s", u.String())
	}
}

func TestNew{{.Bits}}FromWords(t *testing.T) {
	words := [{{.Words}}]uint64{}
	words[{{sub .Words 1}}] = 1
	u := New{{.Bits}}FromWords({{wordNames .Words}})
	if u.String() != "1" {
		t.Fatalf("want 1, got %s", u.String())
	}

	u1 := New{{.Bits}}FromWords({{sampleWordValues .Words}})
	u2, _ := New{{.Bits}}FromBigInt(u1.BigInt())
	if u1 != u2 {
		t.Fatal("round-trip BigInt mismatch")
	}
}

func TestUint{{.Bits}}Arithmetic(t *testing.T) {
	a := New{{.Bits}}(100)
	b := New{{.Bits}}(42)

	sum, err := a.Add(b)
	if err != nil || sum.String() != "142" {
		t.Fatalf("Add: got %v %v", sum, err)
	}

	diff, err := a.Sub(b)
	if err != nil || diff.String() != "58" {
		t.Fatalf("Sub: got %v %v", diff, err)
	}

	if _, err := b.Sub(a); err == nil {
		t.Fatal("Sub underflow: expected error")
	}

	prod, err := a.Mul(b)
	if err != nil || prod.String() != "4200" {
		t.Fatalf("Mul: got %v %v", prod, err)
	}

	quot, err := a.Div(b)
	if err != nil || quot.String() != "2" {
		t.Fatalf("Div: got %v %v", quot, err)
	}

	rem, err := a.Mod(b)
	if err != nil || rem.String() != "16" {
		t.Fatalf("Mod: got %v %v", rem, err)
	}

	if _, err := a.Div(Zero{{.Bits}}()); err == nil {
		t.Fatal("Div by zero: expected error")
	}
}

func TestUint{{.Bits}}Overflow(t *testing.T) {
	m := Max{{.Bits}}()
	if _, err := m.Add(New{{.Bits}}(1)); err == nil {
		t.Fatal("expected overflow error")
	}
	if _, err := m.Mul(New{{.Bits}}(2)); err == nil {
		t.Fatal("expected overflow error")
	}
}

func TestBytes{{.Bytes}}(t *testing.T) {
	u := New{{.Bits}}(256)
	b := u.Bytes{{.Bytes}}()
	if b[{{sub .Bytes 2}}] != 1 || b[{{sub .Bytes 1}}] != 0 {
		t.Fatalf("unexpected bytes: %v", b)
	}
}

func TestUint{{.Bits}}MapKey(t *testing.T) {
	m := map[{{.TypeName}}]string{}
	a, b := New{{.Bits}}(1), New{{.Bits}}(2)
	m[a] = "one"
	m[b] = "two"
	if m[a] != "one" || m[b] != "two" {
		t.Fatal("map key lookup failed")
	}
	a2 := New{{.Bits}}(1)
	if a != a2 {
		t.Fatal("struct equality failed")
	}
}

func TestUint{{.Bits}}Cmp(t *testing.T) {
	a, b := New{{.Bits}}(10), New{{.Bits}}(20)
	if a.Cmp(b) != -1 || b.Cmp(a) != 1 || a.Cmp(a) != 0 {
		t.Fatal("Cmp wrong")
	}
	if !a.Lt(b) || !b.Gt(a) || !a.Lte(a) || !a.Gte(a) {
		t.Fatal("comparison methods wrong")
	}
}

func TestUint{{.Bits}}Bitwise(t *testing.T) {
	a := New{{.Bits}}FromWords({{repeatWord "0" (sub .Words 1)}}, 0b1010)
	b := New{{.Bits}}FromWords({{repeatWord "0" (sub .Words 1)}}, 0b1100)

	if got := a.And(b); got.String() != "8" {
		t.Fatalf("And: got %s, want 8", got)
	}
	if got := a.Or(b); got.String() != "14" {
		t.Fatalf("Or: got %s, want 14", got)
	}
	if got := a.Xor(b); got.String() != "6" {
		t.Fatalf("Xor: got %s, want 6", got)
	}
	if got := a.AndNot(b); got.String() != "2" {
		t.Fatalf("AndNot: got %s, want 2", got)
	}

	if got := a.Not().And(New{{.Bits}}(0xF)); got.String() != "5" {
		t.Fatalf("Not masked low nibble: got %s, want 5", got)
	}

	if got := New{{.Bits}}(1).Lsh(1); got.String() != "2" {
		t.Fatalf("Lsh 1: got %s, want 2", got)
	}
	if got := New{{.Bits}}(8).Rsh(1); got.String() != "4" {
		t.Fatalf("Rsh 1: got %s, want 4", got)
	}

	if got := New{{.Bits}}(1).Lsh(64); got.Cmp(New{{.Bits}}FromWords({{lshOneWords .Words}})) != 0 {
		t.Fatalf("Lsh 64: got %v", got)
	}
	if got := New{{.Bits}}FromWords({{lshOneWords .Words}}).Rsh(64); got.String() != "1" {
		t.Fatalf("Rsh 64: got %s, want 1", got)
	}

	if !New{{.Bits}}(1).Lsh({{.Bits}}).IsZero() {
		t.Fatal("Lsh >= bit width should be zero")
	}
	if !New{{.Bits}}(1).Rsh({{.Bits}}).IsZero() {
		t.Fatal("Rsh >= bit width should be zero")
	}
}
`

func main() {
	bits := flag.Int("bits", 0, "bit width (must be positive multiple of 64)")
	out := flag.String("out", "", "output file path")
	testOut := flag.String("test-out", "", "test output file path")
	withTests := flag.Bool("with-tests", true, "generate a matching _test.go file")
	flag.Parse()

	if *bits <= 0 || *bits%64 != 0 {
		fmt.Fprintln(os.Stderr, "-bits must be a positive multiple of 64")
		os.Exit(2)
	}

	words := *bits / 64
	if *out == "" {
		*out = fmt.Sprintf("uint%d.go", *bits)
	}
	if *testOut == "" {
		*testOut = fmt.Sprintf("uint%d_test.go", *bits)
	}

	d := templateData{
		Bits:      *bits,
		Words:     words,
		Bytes:     *bits / 8,
		TypeName:  fmt.Sprintf("Uint%d", *bits),
		ArrType:   fmt.Sprintf("[%d]uint64", words),
		PreZeros:  repeatWord("0", words-1),
		WordsExpr: wordArgs(words),
	}

	tpl := template.Must(template.New("uint").Funcs(template.FuncMap{
		"repeatWord": repeatWord,
		"sub":        func(a, b int) int { return a - b },
		"sampleWordValues": sampleWordValues,
		"wordNames":  wordNames,
	}).Parse(uintTemplate))

	var buf bytes.Buffer
	if err := tpl.Execute(&buf, d); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := writeFormattedFile(*out, buf.Bytes()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if !*withTests {
		return
	}

	testTpl := template.Must(template.New("test").Funcs(template.FuncMap{
		"sampleWordValues": sampleWordValues,
		"sub":              func(a, b int) int { return a - b },
		"lshOneWords":      lshOneWords,
		"repeatWord":       repeatWord,
		"wordNames":        wordNamesFromArray,
	}).Parse(testTemplate))

	buf.Reset()
	if err := testTpl.Execute(&buf, d); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := writeFormattedFile(*testOut, buf.Bytes()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func writeFormattedFile(path string, src []byte) error {
	formatted, err := format.Source(src)
	if err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}

func repeatWord(word string, n int) string {
	if n <= 0 {
		return ""
	}
	parts := make([]string, n)
	for i := range parts {
		parts[i] = word
	}
	return strings.Join(parts, ", ")
}

func wordArgs(n int) string {
	names := make([]string, n)
	for i := 0; i < n; i++ {
		names[i] = fmt.Sprintf("w%d uint64", i)
	}
	return strings.Join(names, ", ")
}

func wordNames(n int) string {
	names := make([]string, n)
	for i := 0; i < n; i++ {
		names[i] = fmt.Sprintf("w%d", i)
	}
	return strings.Join(names, ", ")
}

func wordNamesFromArray(n int) string {
	names := make([]string, n)
	for i := 0; i < n; i++ {
		names[i] = fmt.Sprintf("words[%d]", i)
	}
	return strings.Join(names, ", ")
}

func sampleWordValues(n int) string {
	vals := make([]string, n)
	for i := 0; i < n; i++ {
		vals[i] = fmt.Sprintf("0x%x", uint64(i+1))
	}
	return strings.Join(vals, ", ")
}

func lshOneWords(n int) string {
	vals := make([]string, n)
	for i := 0; i < n; i++ {
		vals[i] = "0"
	}
	if n >= 2 {
		vals[n-2] = "1"
	}
	return strings.Join(vals, ", ")
}
